Volunteer/urls.py
from django.urls import path
from .views import Join, detail
from . import views

app_name = 'volunteer'

urlpatterns = [
    path('', views.Join, name='Volunteer'),
    path('detail/<int:pk>', views.detail, name ='Detail'),
    path('About/', views.about, name='About'),
]

app4/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'message'
#url for app, add your URL Configuration

urlpatterns = [
    path('', views.message, name='index'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('confirmation/add/', views.add_message, name='add'),
    path('prevention/', views.prevention, name='prevention'),
]

covid_statistic/urls.py
from django.urls import path
from .views import statistic_views, statistic_prov_views
#url for app

app_name = 'stats'
urlpatterns = [
    path('statistic_prov/', statistic_prov_views, name='stats_prov'),
]

fact_checker/urls.py
from django.urls import path
from .views import info_all, info_detail, info_create
#url for app
app_name = 'fact_checker'

urlpatterns = [
    path('<int:check>', info_all, name='info-all'),
    path('', info_all, name='info-all'),
    path('detail/<int:id>/', info_detail, name='info-detail'),
    path('create/', info_create, name='info-create')
]

feedback/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from . import views
app_name = 'feedback'

urlpatterns = [
    path('', views.create_feedback, name='feedback')
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from covid_statistic.views import statistic_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', statistic_views, name='Statistic_Views'),
    path('Fact-Checker/', include('fact_checker.urls')),
    path('statistic/', include('covid_statistic.urls')),
    path('message/', include('app4.urls')),
    path('feedback/', include('feedback.urls')),
    path('Volunteer/', include('Volunteer.urls')),
]

feedback/models.py
from django.db import models

# Create your models here.

class Feedback(models.Model):
    email = models.CharField(max_length=100)
    kritik_saran = models.TextField()

    def __str__(self):
        return f'{self.email}, {self.kritik_saran}'

feedback/forms.py
from django import forms

#import model dari models.py
from .models import Feedback

class FormFeedback(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = [
            'email',
            'kritik_saran'
        ]

        labels = {
            'email' : 'Email',
            'kritik_saran' : 'Kritik/Saran',
        }

        widgets = {
            'email' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                }
            ),

            'kritik_saran' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                }
            ),
        }

feedback/views.py
from django.shortcuts import render, redirect
from .forms import FormFeedback
from .models import Feedback
from django.http import HttpResponseRedirect

# Create your views here.

def create_feedback(request):
    form_feedback = FormFeedback(request.POST or None)

    if request.method == "POST":
        if form_feedback.is_valid():
            form_feedback.save()

            return HttpResponseRedirect('/feedback')
    
    feedback_list = Feedback.objects.all()

    context = {
        'FormFeedback' : form_feedback,
        'page_title' : 'Feedback',
        'feedback_list' : feedback_list
    }
    return render(request, "feedback.html", context)

feedback/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    {% endblock title %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
  crossorigin="anonymous">
  {% block style %}
  {% endblock style %}

</head>

<style>
 .navbar-custom {
   background-color: #154360;
 }
 .navbar-custom .navbar-toggler-icon {
  background-image: url("https://files.catbox.moe/hpcipe.svg");
}

.copyright {
  font-size: 80%;
  color: rgb(229, 229, 229);

}
</style>

<body>
    <nav class="navbar navbar-custom navbar-expand-lg">
        <a style="color: white;" class="navbar-brand" href="{% url 'Statistic_Views' %}">COVINFO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button> 
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a style="color: white;" class="nav-link" href="{% url 'Statistic_Views' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a style="color: white;" class="nav-link" href="{% url 'volunteer:About' %}">About</a>
            </li>
            <li class="nav-item">
              <a style="color: white;" class="nav-link" href="{% url 'stats:stats_prov' %}">Cases</a>
            </li>
            <li class="nav-item">
              <a style="color: white;" class="nav-link" href="{% url 'message:prevention' %}">Prevention</a>
            </li>
            <li class="nav-item dropdown">
              <a style="color: white;" class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Other
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'fact_checker:info-all' %}">Fact Checker</a>
                <a class="dropdown-item" href="{% url 'volunteer:Volunteer' %}">Volunteer</a>
                <a class="dropdown-item" href="{% url 'feedback:feedback' %}">Feedback</a>
                <a class="dropdown-item" href="{% url 'message:index' %}">Hopeful Message</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    <div class="container" >
        {% block content %}

        {% endblock content %}
      <br>
      <br>
      <p class="copyright">© Kelompok 14 PPW Kelas D 2020, Fakultas Ilmu Komputer, Universitas Indonesia</p>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" 
integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" 
crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" 
integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" 
crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" 
integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" 
crossorigin="anonymous"></script>
  
</body>

</html>

feedback/templates/feedback.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    <title>Feedback</title>
{% endblock page_title %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'stylefb.css' %}">
{% endblock style %}

{% block content %}
    <h1>Feedback</h1>
    <br>
    <div class="container">
        <div class="row">
            <div id= "col1" class="col">
                <div class="container-fluid">
                    {% for i in feedback_list %}
                    <div class="mini-block">
                        <ul class="row justify-content-start">
                            <p style="color:#154360;">
                                <b>{{ i.email }}</b>
                                <br>
                                {{ i.kritik_saran }}
                            </p>
                            
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col">
                <div class="container-fluid">
                    <form class="main-form" id="form" method="POST">
                        {% csrf_token %}
                        {% for form in FormFeedback %}
                            <div class="form-group">
                                {{form.label}}
                                {{form}}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-success float-right" style="background-color: #154360; color:#FCA311">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}