fact_checker/urls.py
from django.urls import path
from .views import info_all, info_detail, info_create
#url for app
app_name = 'fact_checker'

urlpatterns = [
    path('<int:check>', info_all, name='info-all'),
    path('', info_all, name='info-all'),
    path('detail/<int:id>/', info_detail, name='info-detail'),
    path('create/', info_create, name='info-create')
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from covid_statistic.views import statistic_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', statistic_views, name='Statistic_Views'),
    path('Fact-Checker/', include('fact_checker.urls')),
    path('statistic/', include('covid_statistic.urls')),
    path('message/', include('app4.urls')),
    path('feedback/', include('feedback.urls')),
    path('Volunteer/', include('Volunteer.urls')),
]

fact_checker/models.py
from django.db import models

# Create your models here.
class FactCheck(models.Model):
    # User can Access
    title = models.CharField(max_length=100)
    user_name = models.CharField(max_length=100)
    user_info = models.TextField()

    # Admin only
    is_checked = models.BooleanField(default=False)
    clarification = models.TextField()

    def __str__(self):
        return self.title

fact_checker/forms.py
from django.db.models import fields
from django import forms
from django.forms import ModelForm, Textarea, TextInput, DateInput
from django.forms import widgets
from .models import FactCheck

class FactCheckForm(ModelForm):
    class Meta:
        model = FactCheck
        fields = ['title','user_name','user_info']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'ex: Hoax on social media', 'required': True}),
            'user_name': TextInput(attrs={'placeholder': 'ex: John Smith', 'required': True}),
            'user_info': TextInput(attrs={'placeholder': 'Fill out your information here', 'required': True}),
            }

fact_checker/views.py
from django.shortcuts import render, redirect
from .models import FactCheck
from .forms import FactCheckForm

# Create your views here.
def info_all(request,check=0):
    unfiltered_fact_check = FactCheck.objects.all()
    confirmed = []
    unconfirmed = []
    confirmation = ""
    for i in unfiltered_fact_check:
        if i.is_checked:
            confirmed.append(i)
        else:
            unconfirmed.append(i)

    if check == 1:
        confirmation = "Your report has been submitted!"

    context = {
                'confirmed': confirmed,
                'unconfirmed' : unconfirmed,
                'confirmation':confirmation
    }

    return render(request, 'info_all.html', context)

def info_detail(request,id):
    obj = FactCheck.objects.get(id=id)
    context = {'info' : obj}
    return render(request, 'info_detail.html',context)

def info_create(request):
    form = FactCheckForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('fact_checker:info-all',check = 1)
    context = {'form':form}
    return render(request, 'info_create.html', context)

fact_checker/templates/info_all.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title> Fact Checker </title>
{% endblock title %}

{% block style %}
    <link rel="stylesheet" type="text/css"  href="{% static 'css/fact_checker.css' %}">
{% endblock style %}
   {% block content  %}
        {% if confirmation != "" %}
            <div class="alert alert-secondary" role="alert">
                {{ confirmation }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
        {% endif %}
        <br>
        <h1 class="font-dark-blue bold">Fact Checker</h1>
        <br>
        <a class="btn btn-warning" href="{% url 'fact_checker:info-create' %}" role="button">Create Report</a>
        <br>
        <br>
        <div class="grey-card">
            <div class="container">
                <br>
                <h3 class="font-black bold">Fact Checked</h3>
                <br>
                {% if confirmed %}
                    {% for i in confirmed %}
                    <div>
                        <p class="font-yellow bold"><a href="{% url 'fact_checker:info-detail' i.id %}">{{ i.title }}</a></p>
                        <p class="font-black">{{ i.user_info|truncatechars:395 }}</p>
                    </div>
                    <br>
                    {% endfor %}
                {% else %}
                    <br>
                    <br>
                         <p class="font-black-muted d-flex justify-content-center">Nothing to display here</p>
                    <br>
                    <br>
                {% endif %}
            </div>
        </div>

        <br>

        <div class="grey-card">
            <div class="container">
                <br>
                <h3 class="font-black bold">Reported</h3>
                <br>
                {% if unconfirmed %}
                    {% for i in unconfirmed %}
                    <div>
                        <p class="font-yellow bold"><a href="{% url 'fact_checker:info-detail' i.id %}">{{ i.title }}</a></p>
                        <p class="font-black">{{ i.user_info|truncatechars:195 }}</p>
                    </div>
                    <br>
                    {% endfor %}
                {% else %}
                    <br>
                    <br>
                        <p class="font-black-muted d-flex justify-content-center">Nothing to display here</p>
                    <br>
                    <br>
                {% endif %}
            </div>
        </div>
    {% endblock  %}

fact_checker/templates/info_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title> Fact Checker | Create </title>
{% endblock title %}

{% block style %}
    <link rel="stylesheet" type="text/css"  href="{% static 'css/fact_checker.css' %}">
{% endblock style %}

{% load crispy_forms_tags %}
    {% block content  %}
    <form method = "POST">
        {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-warning" type="submit" value="Submit">
        </form>
    {% endblock %}

fact_checker/templates/info_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title> Fact Checker | Detail </title>
{% endblock title %}

{% block style %}
    <link rel="stylesheet" type="text/css"  href="{% static 'css/fact_checker.css' %}">
{% endblock style %}
    {% block content  %}
        <h1 class= "font-dark-blue bold"> {{ info.title }}</h1>
        <p class="font-black-muted"> Submitted by : {{ info.user_name }}</p>
        <div class="grey-card">
            <div class="container">
            <br>
                <p>{{ info.user_info }}</p>
            <br>
            </div>
        </div>
        <br>
        <h1 class= "font-yellow bold"> Clarification </h1>
        <br>

        <div class="grey-card">
        <div class="container">
            {% if info.clarification  %}
            <br>
                <p>{{ info.clarification }}</p>
            <br>
            {% else %}
            <br>
            <br>
                <p class="font-black-muted d-flex justify-content-center">Nothing to display here</p>
            <br>
            <br>
        {% endif %}
        </div>
        </div>
    {% endblock %}