Volunteer/urls.py
from django.urls import path
from .views import Join, detail
from . import views

app_name = 'volunteer'

urlpatterns = [
    path('', views.Join, name='Volunteer'),
    path('detail/<int:pk>', views.detail, name ='Detail'),
    path('About/', views.about, name='About'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from covid_statistic.views import statistic_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', statistic_views, name='Statistic_Views'),
    path('Fact-Checker/', include('fact_checker.urls')),
    path('statistic/', include('covid_statistic.urls')),
    path('message/', include('app4.urls')),
    path('feedback/', include('feedback.urls')),
    path('Volunteer/', include('Volunteer.urls')),
]

Volunteer/models.py
from django.db import models

# Create your models here.
class Volunteer(models.Model):
    Nama = models.CharField(max_length=50)
    Tujuan = models.CharField(max_length=50)
    Kontak = models.CharField(max_length=50)

    # def __str__(self):
    #     return self.Nama

Volunteer/forms.py
from django import forms

class VolunteerForm(forms.Form):

    Nama = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Masukkan Nama',
        'type' : 'text',
        'required': True,
    }))

    Tujuan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Volunteer atau Membutuhkan',
        'type' : 'text',
        'required': True,
    }))

    Kontak = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Masukkan Kontak',
        'type' : 'text',
        'required': True,
    }))

Volunteer/views.py
from django.shortcuts import render, redirect
from .models import Volunteer as donator
from .forms import VolunteerForm

def Join(request):
    form = VolunteerForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            volun = donator()
            volun.Nama = form.cleaned_data['Nama']
            volun.Tujuan = form.cleaned_data['Tujuan']
            volun.Kontak = form.cleaned_data['Kontak']
            volun.save()
            return redirect('/Volunteer')
    
    volun = donator.objects.all()
    form = VolunteerForm()
    response = {"volun":volun, 'form' : form}
    return render(request,'Volunteer.html',response)

# def volun_delete(request, pk):
#     form = VolunteerForm(request.POST)
#     if request.method == "POST":
#         if form.is_valid():
#             volun = donator()
#             volun.Nama = form.cleaned_data['Nama']
#             volun.Tujuan = form.cleaned_data['Tujuan']
#             volun.Kontak = form.cleaned_data['Kontak']
#             volun.save()
#             return redirect('/Volunteer')
    
#     donator.objects.filter(pk=pk).delete()
#     data = donator.objects.all()
#     form = VolunteerForm()
#     response = {"volun":data, 'form' : form}
#     return render(request, 'Volunteer.html', response)

def detail(request, pk):
    volun = donator.objects.all().filter(id=pk)
    response = {"VolunteerForm" : volun}
    return render(request, "detail.html", response)

def about(request):
    return render(request, 'About.html')
    

Volunteer/templates/About.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  <title>About</title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'about.css' %}">
{% endblock style %}

{% block content %}
<br>
<div class="row">
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
    <img class="img-responsive" src="{% static 'covid.png' %}" >
  </div>
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
      <h2 class="text">
        <b>Covinfo</b> akan memberikan informasi mengenai akumulasi 
        kasus covid-19 di setip provinsi di Indonesia. Covinfo dibuat oleh mahasiswa Fakultas Ilmu Komputer Universitas Indonesia untuk memenuhi tugas pada mata kuliah Program Perancangan Web semester 3. Melalu website ini diharapkan mampu memberi informasi kepada masyarakat Indonesia terkain kasus dan cara pencegahan penularan dari covid-19.
      </h2>
  </div>
</div>
{% endblock content %}

Volunteer/templates/Volunteer.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Volunteer</title>
{% endblock title %}

{% block style %}
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" type = "text/css"  href = "{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:700&display=swap"rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700&display=swap" rel="stylesheet">
{% endblock style %}

{% block content %}
    <div style="margin: 55px"> 
        <div id = "Salam">
                <h1><p style="color:darkblue">Volunteer</p></h1>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <form action='' method="POST">
                            {% csrf_token %}
                            {{ form }}
                        <div class="centre-items">
                            <input type="submit" class="btn btn-warning" value="Submit">
                        </div>
                        </form>
                    </div>
                    <div class="col" id="tulisan">
                        <table  class="table">
                            <thead>
                                <tr>
                                <th scope="col"><p style="color:orange;">Nama</p></th>
                                <th scope="col"><p style="color:orange;">Tujuan</p></th>
                                <th scope="col"><p style="color:orange;">Kontak</p></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for donator in volun %}
                                    <tr>
                                    <th scope="row"><a href="{% url 'volunteer:Detail' donator.id %}">{{donator.Nama}}</a></th>
                                    <td>{{donator.Tujuan}}</td>
                                    <td>{{donator.Kontak}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
             </div>
{% endblock content %}

Volunteer/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
     <title>Detail Mata Kuliah</title>
{% endblock title %}

{% block style %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|PT+Serif:400,700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/home/style2.css">
    <link rel="stylesheet" href="../../static/home/mobile-style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
{% endblock style %}


{% block content %}
<div class="main-content">
<link rel="stylesheet" href="/static/home/Story5.css">

<style>
    body{
        background:url("/static/salju.jpeg");
        padding-bottom: 65vw;
        background-size: cover;
        font-family: Arial, Helvetica, sans-serif;
    }
    </style>

    <div class="container">
        <h1 class="text-center">
             Detail Volunteer
        </h1>
        <p>
        </p>
    <br>
    <table class="table table-striped table-dark">
        {% for Volunteer in VolunteerForm %}
            <tbody><tr>
                <td id="detail_keterangan">Nama</td>
                <td id="detail_penjelasan">{{Volunteer.Nama}}</td>
            </tr>
            <tr>
                <td id="detail_keterangan">Tujuan</td>
                <td id="detail_penjelasan">{{Volunteer.Tujuan}}</td>
            </tr>
            <tr>
                <td id="detail_keterangan">Kontak</td>
                <td id="detail_penjelasan">{{Volunteer.Kontak}}</td>
            </tr>
        </tbody>
        {% endfor %}
        </table>
      <div class="text-center">
        <a class="btn btn-sm btn-dark" href="/Volunteer">Kembali</a>
      </div>
    </div>


    </div>
{% endblock content %}