app4/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'message'
#url for app, add your URL Configuration

urlpatterns = [
    path('', views.message, name='index'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('confirmation/add/', views.add_message, name='add'),
    path('prevention/', views.prevention, name='prevention'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from covid_statistic.views import statistic_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', statistic_views, name='Statistic_Views'),
    path('Fact-Checker/', include('fact_checker.urls')),
    path('statistic/', include('covid_statistic.urls')),
    path('message/', include('app4.urls')),
    path('feedback/', include('feedback.urls')),
    path('Volunteer/', include('Volunteer.urls')),
]

app4/models.py
from django.db import models

# Create your models here.
class MessageAndExpectation(models.Model):
    name = models.CharField(max_length=50)
    message = models.TextField()

app4/forms.py
from django import forms
from app4.models import MessageAndExpectation


class MessageAndExpectationForm(forms.ModelForm):
    class Meta:
        model = MessageAndExpectation
        fields = (
            'name',
            'message',
        )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control'}),
        }

app4/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import inlineformset_factory, modelformset_factory
from app4.forms import MessageAndExpectationForm
from app4.models import MessageAndExpectation


# Create your views here.
def message(request):
    message = MessageAndExpectation.objects.all()
    form = MessageAndExpectationForm()
    context = {
        'message': message,
        'form': form,
    }
    return render(request, 'message.html', context)

def confirmation(request):
    if request.method == "POST":
        form = MessageAndExpectationForm(request.POST)
        context = {
            'form': form,
            'name': request.POST['name'],
            'message': request.POST['message']
        }
        return render(request, 'confirmation.html', context)
    else:
        return redirect('message:index')

def add_message(request):
    if request.method == "POST":
        form = MessageAndExpectationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('message:index')
    else:
        return redirect('message:index')

def prevention(request):
    return render(request, 'prevention.html')

app4/templates/confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Confirmation</title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'message.css' %}">
{% endblock style %}

{% block content %}
<div class="d-flex flex-column pt-5 align-items-center container wrapper">
    <div class="col-md-8">
        <form action=" {% url 'message:add' %}" class="main-form" method="POST">
            {% csrf_token %}
            <div class="d-none">
                {{ form }}
            </div>
            <div class="card text-center">
                <div class="card-header">
                    Confirmation
                </div>
                <div class="card-body">
                    <h5 class="card-title">Halo, {{ name }}</h5>
                    <p class="card-text">Tambahkan pesan ini?</p>
                    <h4 class="text text-center" style="color: #FCA311;"><span>&#x201c</span>{{ message }}<span>&#x201d</span></h4>
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'message:index' %}" class="btn btn-secondary mr-2">Batal</a>
                        <button class="btn btn-success mr-2" type="submit">Tambah</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock content %}

app4/templates/message.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Message</title>
{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static 'message.css' %}">
{% endblock style %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="column">
            <div class="container-fluid">
                <h2 class="text-center">Kolom Pesan</h2>
                <form action="{% url 'message:confirmation' %}" class="main-form" id="form" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Nama</label>
                        <br>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label for="name">Pesan</label>
                        <br>
                        {{ form.message }}
                    </div>
                    <button type="submit" class="btn btn-success mb-3 float-right">Tambah</button>
                </form>
            </div>
        </div>
        <div class="column">
            <div class="container-fluid">
                <h2 style="text-align: center;">Pesan dan Harapan</h2>
                {% for i in message %}
                <div class="mini-block">
                    <ul class="row justify-content-start">
                        <p style="color: #FCA311;">
                            <b>{{ i.name }}</b>
                            <br>
                            {{ i.message }}
                        </p>
                    </ul>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app4/templates/prevention.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Confirmation</title>
{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static 'prevention.css' %}">
{% endblock style %}

{% block content %}

<div class="container-fluid">
    <div class="d-flex justify-content-center">
        <div class="col-3 ml-2">
            <div class="container-fluid">
                <img src="{% static '1_Xn_7ZpYbGAszWlotIOhLIQ.jpeg' %}" class="img-fluid" alt="Responsive image">
                <div class="block">
                    <p>Menggunakan Masker</p>
                </div>
            </div>
        </div>
        <div class="col-3 ml-2">
            <div class="container-fluid">
                <img src="{% static 'physical-distancing-4986940_1280.jpg' %}"  class="img-fluid" alt="Responsive image">
                <div class="block">
                    <p>Menjaga Jarak</p>
                </div>
            </div>
        </div>
        <div class="col-3 ml-2">
            <div class="container-fluid">
                <img src="{% static 'Eck83SEXoAATDcE.jpg' %}"  class="img-fluid" alt="Responsive image">
                <div class="block">
                    <p>Mencuci Tangan</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}